<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="admin-PC" ignored="0" name="NewTest" tests="6" failures="1" timestamp="07 Jul 2019 11:42:29 GMT" time="54.993" errors="0">
  <testcase name="Test1" time="0.014" classname="com.qa.retryfailedtestcases.Rahul.ScreenshotFailedTestCases"/>
  <testcase name="Test2" time="0.007" classname="com.qa.retryfailedtestcases.Rahul.ScreenshotFailedTestCases"/>
  <testcase name="Test3" time="0.004" classname="com.qa.retryfailedtestcases.Rahul.ScreenshotFailedTestCases">
    <skipped/>
  </testcase> <!-- Test3 -->
  <testcase name="Test3" time="0.013" classname="com.qa.retryfailedtestcases.Rahul.ScreenshotFailedTestCases">
    <skipped/>
  </testcase> <!-- Test3 -->
  <testcase name="Test3" time="0.003" classname="com.qa.retryfailedtestcases.Rahul.ScreenshotFailedTestCases">
    <skipped/>
  </testcase> <!-- Test3 -->
  <testcase name="Test3" time="0.002" classname="com.qa.retryfailedtestcases.Rahul.ScreenshotFailedTestCases">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.qa.retryfailedtestcases.Rahul.ScreenshotFailedTestCases.Test3(ScreenshotFailedTestCases.java:48)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- Test3 -->
</testsuite> <!-- NewTest -->
